CC = g++

padrao:
	$(CC) mainConventional.cpp -o main 

otimizado:
	$(CC) mainOptimized.cpp -o main 

# otimizado1:
# 	$(CC) mainCpp.cpp -O1 -o main 

# otimizado2:
# 	$(CC) mainCpp.cpp -O2 -o main 

# otimizado3:
# 	$(CC) mainCpp.cpp -O3 -o main 

clean:
	rm main