CC = g++

padrao:
	$(CC) final_project.cpp -o main 

otimizadoMemoria:
	$(CC) final_project_memoryotm.cpp -o main 

otimizadoMemoriaDir1:
	$(CC) final_project_memoryotm.cpp -O1 -o main

otimizadoMemoriaDir2:
	$(CC) final_project_memoryotm.cpp -O2 -o main

otimizadoMemoriaDir3:
	$(CC) final_project_memoryotm.cpp -O3 -o main

paralelo:
	$(CC) final_project_parallel.cpp -O3 -o main

clean:
	rm main